### ISSUE TITLE
Recalc shipping also

### ISSUE THREAD

**Issue by NickGreen** [Prospress/woocommerce-subscriptions-recalculate-totals#4]
https://secure.helpscout.net/conversation/753606769/26344?folderId=1524435

I've encountered a situation where it would be nice to be able to recalc shipping as well.

For now, I've hacked it to remove the shipping line item entirely by using `$subscription->remove_order_items('shipping');`, which is what I needed in this case.

However, it might be nice to be able to selectively recalc shipping in the same way that we are recalculating taxes.

**Comment by thenbrent** [comment]
I wrote a _Remove Shipping_ action for AutomateWoo yesterday that hopefully will be public next month sometime and can be used in beta prior to that if needed.

I think it's better if we encourage folks to use that for bulk updates like this as it also comes with background processing, error handling and better logging, rather than adding this as an additional feature to this plugin. :)
